/**
 * Generated by `tools/laptop/build_laptop.py`. Do not edit by hand — rerun the
 * build script instead, or the numbers here and the geometry in
 * `public/models/laptop.glb` will disagree.
 *
 * Three.js axes, not Blender's. The exporter converts Z-up to Y-up, so a
 * measurement taken along Blender's +Y — towards the back of the machine — is
 * read here along -Z.
 */

export const LAPTOP = {
  /** Overall width, in scene units. */
  width: 3.00000,
  /** Front-to-back depth of the base. */
  depth: 2.05870,
  /** Height of the base alone. */
  baseHeight: 0.10653,
  /** Height of the closed machine, lid included. */
  closedHeight: 0.15307,
  /** Hinge axis, relative to the model's own origin. */
  hinge: { y: 0.13196, z: -1.00824 },
  /** Hinge to the far edge of the lid. */
  lidLength: 2.03759,
  /** Panel size, for framing the camera on the display. */
  panel: { width: 2.85413, height: 1.85333 },
  /** Panel centre above the hinge axis, measured along the lid. */
  panelCentre: 1.03799,
  /** Panel surface out from the hinge axis, along the lid's normal. */
  panelFace: 0.01987,
  /** Resting open angle, in radians, measured from upright. */
  openAngle: -0.29671,
  /** Shut: a quarter turn forward from upright. */
  closedAngle: Math.PI / 2,
} as const;
